### ISSUE TITLE
The App not work in the cluster which is 8 roles in multi-VMs.

### ISSUE THREAD

**Issue by WangShengLin1986** [AppScale/appscale#1564]
https://groups.google.com/forum/#!topic/appscale_community/TkBaIomNAIk

config file:
ips_layout :
  master : 192.168.51.1
  database : 192.168.51.2
  appengine : 
  - 192.168.51.3
  - 192.168.51.4
  open : 192.168.51.5
  login : 192.168.51.6
  zookeeper : 192.168.51.7
  memcache : 192.168.51.8
  taskqueue : 192.168.51.9

when I upload the guestbook.tar.gz at this appscale (9 VMs).

There was an error uploading your application: AppScale did not find the correct SDK jar versions in your app. The current supported SDK version is 1.8.0.

BTW, when I chick the TaskQueue Monitor, the url is "http://192.168.51.1:5555/" not "http://192.168.51.6:5555/", please check, thank you. And the worker is empty, is it normal??

**Comment by obino** [comment]
Can you still see this issue on the latest appscale version (2.5.0)? The warning about the SDK shouldn't be fatal.

**Comment by menivaitsi** [comment]
Closing as inactive.
