### ISSUE TITLE
DataStore sharing between apps

### ISSUE THREAD

**Issue by barakcoh** [AppScale/appscale#1686]
According to the wiki AppScale doesn't support modules which is unfortunate as it excludes a large number of apps from using it. Can we deploy each module as a separate app and have them share the same DataStore instance?

**Comment by nlake44** [comment]
Yes. You'll have to map all the different app IDs to the same backend ID. See appscale/AppDB/datastore_server.py and look for "clean_app_id". See the following gist:
https://gist.github.com/nlake44/96ae5393450a7ceff99e for the code you'd you have to modify.

Each app ID would share the same prefix: my-app-1, my-app-2, etc, where your prefix would be "my-app". There might be some checks on the application server side if the application IDs don't match, so you'll have to disable those checks if they exists.

Let me know if you try this out and run into any issues.

**Comment by nlake44** [comment]
Optionally you can use remote-api in your application. But the previous method would probably require less code changes.

**Comment by sjuncal11** [comment]
Closin issues like a G!

Shaun
