### ISSUE TITLE
appscale crash

### ISSUE THREAD

**Issue by tadcos** [AppScale/appscale#1692]
I tried AppScale using default configuration. I correctly access to the dashboard at https://192.168.33.10:1443/ and  to an application at http://192.168.33.10:8080/
I have also access to http://192.168.33.10:8080/_ah/admin/ where I can view the datastore.
But if I clic on "Task Queue", AppScale crashes and the server hangs. There is no more accesss to the previous URLs.

**Comment by nlake44** [comment]
Task Queue in the admin console?

**Comment by obino** [comment]
Closing this issue for lack of feedback: feel free to re-open with more info.
