### ISSUE TITLE
Upgrade App Engine to 1.8.9

### ISSUE THREAD

**Issue by caseyoneill** [AppScale/appscale#1711]
My company would like to request that the App Engine libraries be upgraded to 1.8.9. Google fixed many bug between 1.8.0 and 1.8.9 and we would like to see those fixes also brought to AppScale. As is detailed in this post https://groups.google.com/forum/#!topic/appscale_community/ihbp8RSZ7hM  , 1.8.0 would not allow a Hibernate JPA connection to work with MySQL. Upgrading to AppEngine 1.8.1 using this fork fixed the issue: https://github.com/caseyoneill/appscale/tree/1.8.1-java-upgrade .

**Comment by caseyoneill** [comment]
We understand that the AppScale team is working on many important enhancements and valuable features so we would like to volunteer to handle the grunt work of merging in the changes for each App Engine point release. I've already submitted a Pull Request to upgrade Java to 1.8.1 and would be to do the same for Python as well.

**Comment by obino** [comment]
Thanks @caseyoneill awesome work. We will review the pull soon. Feel free to submit also the python branch and we'll review it.
