### ISSUE TITLE
Error in package finding in golang

### ISSUE THREAD

**Issue by onlyangel** [AppScale/appscale#1716]
I get:
`2015/04/12 22:14:35 Can't find package "github.com/go-sql-driver/mysql" in $GOPATH: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/root/appscale/AppServer/gopath/src/pkg/github.com/go-sql-driver/mysql (from $GOROOT)
	/root/appscale/AppServer/goroot/src/github.com/go-sql-driver/mysql (from $GOPATH)
2015/04/12 22:14:36 go-app-builder: build timing: 7Ã—6g (237.372602ms total), 6Ã—gopack (28.930674ms total), 0Ã—6l (0 total)
2015/04/12 22:14:36 go-app-builder: failed running 6g: exit status 1
`

The compiler is searching in 
`/root/appscale/AppServer/gopath/src/pkg/{packageurl}` when it suposes to be `/root/appscale/AppServer/gopath/src/{packageurl}`
and in
`/root/appscale/AppServer/goroot/src/{packageurl}`when it suposes to be `/root/appscale/AppServer/goroot/src/pkg/{packageurl}`

As seen in the filesystem.

**Comment by onlyangel** [comment]
I think I can create a patch for this. Let me clone the repo.

**Comment by obino** [comment]
@onlyangel thanks!
