### ISSUE TITLE
Login redirect URLs start with 'http'

### ISSUE THREAD

**Issue by cdonati** [AppScale/appscale#1733]
The url parameter `continue` always starts with http when visiting an app's login page.

This happens regardless of whether or not `secure: always` is set in app.yaml. However, it's less of an issue in this case because when the browser tries fetching the http URL, it will get redirected to the https version.

Here's the line where this URL is generated: https://github.com/AppScale/appscale/blob/master/AppServer/google/appengine/tools/devappserver2/url_handler.py#L140

**Comment by uskudnik** [comment]
:+1:

**Comment by cdonati** [comment]
This is now fixed in master.
