### ISSUE TITLE
max_memory monit

### ISSUE THREAD

**Issue by korvyashka** [AppScale/appscale#1735]
It seems, that generated monit file for node doesn't have updated max_memory from local AppScaleFile, and 500mb is taken always.

"if totalmem > 500 MB for 10 cycles then restart"
in generated monit file.

**Comment by menivaitsi** [comment]
Do you see that in the monit config for your application's appengine servers? Or for another AppScale component?
Currently you can only tweak the appengine servers from within your AppScalefile. 
I believe it's preset to 400 MB.

**Comment by korvyashka** [comment]
Yes - I saw it in generated monit configs for application node in format app___appname... while number in Appscalefile was different.
But currently I can't repeat it - might be it gone after rebooting vagrant, 
so I am closing issue.

**Comment by korvyashka** [comment]
Got it again and now understands when it happened:

First generated config for application is ok(after appscale deploy command):
app___appname-20000.cfg

``` bash
  if totalmem > 1000 MB for 10 cycles then restart
```

But config generated dynamicly after, got default value:
app___appname-20001.cfg
``` bash
  if totalmem > 500 MB for 10 cycles then restart
```
According to doc it happened when " If it exceeds 5 requests per second (a value you can change if you like) on a given machine, then the AppController on that machine adds an application server."

**Comment by obino** [comment]
@korvyashka let us know if you see this issue again: we routinely test with larger values and we haven't observed that behavior in 3.2.
