### ISSUE TITLE
Fragment identifier gets truncated if user is not logged in

### ISSUE THREAD

**Issue by uskudnik** [AppScale/appscale#1739]
If user gets a link and is at the moment not logged in he gets a login window (as expected) but does not get redirected to the correct target URL after he gets logged in if that URL contains fragment identifier (`#`).

The URL `login=next` parameter in the URL itself is correct and contains the entire URL but the `continue` hidden field does not - it has an URL with `login?next=` parameter supplied but truncated at the `#` character.

**Comment by cdonati** [comment]
I can confirm that the fragment identifier is lost during the call to `self.request.get('continue')`. In my testing, however, I found that this behavior also exists on both the SDK and App Engine. For that reason, I'm going to close this issue for now.
