### ISSUE TITLE
Java Blob Uploads from Mobile App Crashes

### ISSUE THREAD

**Issue by caseyoneill** [AppScale/appscale#1740]
It appears that there are two different routes that can be taken when uploading a blob. Web uploads, as tested by the Blobstore sample app, will execute without error. However, blob uploads that happen from a mobile app and through an API end up crashing. I suspect the difference is that the web has a session and the API request creates a unique session just for the upload, but I haven't been able to prove that to be the difference. 

I have created a test application that can be downloaded here: https://dl.dropboxusercontent.com/u/8314200/UploadTest.zip . This project tests both upload paths and I suggest that you read the README.txt for more detailed instructions. The basics are that uploading through /index.jsp works just fine. However, once the app is deployed, uploading through the MobileClient.java class will cause the server to throw an exception. 

I've created a [patch](https://github.com/caseyoneill/appscale/commit/e2ea371698c42982e2e39aa9f79a610c7d301d41) that fixes a couple of bugs in BlobUploadSessionStorage. However, because the uploads seem to execute in two different manners, the web upload through /index.jsp now throws a 500 error because it doesn't know how to use a relative URL redirect to the app server from the 6067 blob server. It's unclear to me why the mobile upload would understand how to handle a relative url redirect and why the web upload would not.

**Comment by menivaitsi** [comment]
This issue has been fixed in the current AppScale master. It will be part of the next release.
