### ISSUE TITLE
Broken link in appscale_build.sh

### ISSUE THREAD

**Issue by emmanuel-florent** [AppScale/appscale#1744]
Can anyone fix the download or the link provided ?
While running  bash appscale_build.sh 
root@webrtc:~/appscale/debian# curl -i http://s3.amazonaws.com/appscale-build/monit-5.6-prebuilt-trusty.tar.gz
HTTP/1.1 403 Forbidden
(No mirror as googling ?!)

Thanks for  Your Amazing Work on an Awesome Platform.

**Comment by obino** [comment]
Hello, thanks for the kind words.  I think you are using a developer branch, or you are trying to install appscale on trusty: at this time we support precise.

**Comment by emmanuel-florent** [comment]
Yes that's right I'm trying to install on Trusty.
But if I revert back to Precise Pangolin I won't have the same behaviour ?

2015-06-16 21:01 GMT+00:00 graziano obertelli <notifications@github.com>:

**Comment by obino** [comment]
Correct: also the newer version of appscale uses the system's version of monit.
