### ISSUE TITLE
Bootstrap script / Install ruby dev

### ISSUE THREAD

**Issue by fhibler** [AppScale/appscale#1830]
On a plain Ubuntu 14.04 installation "ruby-dev" is missing and not installed automatically by using the bootstrap script as per https://github.com/AppScale/appscale/wiki/Installing-AppScale-from-source-on-GitHub

The following error will occur:

```
Generating /etc/appscale/environment.yaml
APPSCALE_HOME: /root/appscale
EC2_HOME: /usr/local/ec2-api-tools
JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
Successfully installed rake-10.4.2
1 gem installed
Building native extensions.  This could take a while...
ERROR:  Error installing zookeeper:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/zookeeper-1.4.11 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/zookeeper-1.4.11/ext/gem_make.out
failed!
```

This can be fixed by adding the package `ruby-dev` to the required packages to be installed via apt.

**Comment by obino** [comment]
We believe this is fixed. We have a control-trusty that does exactly that. Note that at this time we don't quite support anything past precise: we still have regression issues.
