### ISSUE TITLE
appscale-tools arguments

### ISSUE THREAD

**Issue by zeroluck** [AppScale/appscale#1855]
It would be useful as an enhancement to appscale-tools to be able to add the desired email address as an argument to `appscale deploy app` for automation purposes, i.e. `appscale deploy appname -c admin@domain`.

This would allow scripts, puppet, spacewalk and other automation tools to deploy apps without human intervention.

**Comment by menivaitsi** [comment]
Good point @zeroluck. 

For now you can use:
appscale-upload-app --file </path/to/your/app> --email <app_owner> --keyname <keyname_from_your_AppScalefile>
