### ISSUE TITLE
LDAP Authentication?

### ISSUE THREAD

**Issue by zeroluck** [AppScale/appscale#1870]
Reading: https://github.com/AppScale/appscale/wiki/Managing-Users and https://github.com/AppScale/appscale/wiki/UserAppServer

There is mention of an LDAP plugin for user authentication. Does this exist already? I have checked the file appscale/AppDB/soap_server.py and there doesn't seem to be any other functionality in there.

I also see that someone published a book with this information here: https://goo.gl/pyzjYE

**Comment by obino** [comment]
Hello @zeroluck, we do have work in the code to have AppScale to work with Shibboleth. So we do work indirectly with LDAP via Shibboleth, but we don't have direct support for AD or LDAP at this time out of the box.

**Comment by zeroluck** [comment]
I am implementing Shibboleth idP using gluu to connect to AppScale: https://github.com/GluuFederation/oxIdp https://www.gluu.org/. Since you guys don't have a whole lot of documentation on implementing the shibboleth functionality of AppScale yet, I was wondering if you had any tips. Here is gluu's documentation on setting up outbound SAML: https://www.gluu.org/docs/admin-guide/saml/outbound-saml/

Specifically, I am curious about what I should fill in for the metadata. Does your implementation use the Shibboleth SP? If that is the case, should I maybe try using their Generate option since they say it is directly compatible with the Shibboleth SP?

**Comment by cdonati** [comment]
Hi @zeroluck,

Yes, the `SHIBBOLETH_CONNECTOR` field in the AppDashboardHelper is for specifying an SP server. I'm not familiar with the Gluu service, but here's a rough apache vhost configuration example that may help if you're setting up an SP:
```
<VirtualHost _default_:443>
    ServerName your.shibboleth.sp.dns

    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off

    ProxyPass /shibboleth/ !
    ProxyPassReverse /shibboleth/ !
    ProxyPass /shibboleth !
    ProxyPassReverse /shibboleth !
    ProxyPass /Shibboleth.sso/ !
    ProxyPassReverse /Shibboleth.sso/ !
    ProxyPass /shibboleth-sp !
    ProxyPassReverse /shibboleth-sp !

    ProxyPass / https://your-appscale-server:1443/ retry=0 timeout=5
    ProxyPassReverse / https://your-appscale-server:1443/

    <FilesMatch "\.(cgi|shtml|phtml|php)$">
        SSLOptions +StdEnvVars
    </FilesMatch>
    <Directory /usr/lib/cgi-bin>
        SSLOptions +StdEnvVars
    </Directory>

    <Location />
        AuthType shibboleth
        Require shibboleth
        ShibUseHeaders On
    </Location>

    <Location /Shibboleth.sso>
        SetHandler shib
    </Location>

    <Location /shibboleth>
        SetHandler shib
    </Location>

    Alias /shibboleth-sp /etc/shibboleth/static
    <Directory /etc/shibboleth/static>
        Order allow,deny
        Allow from all
        Options +Indexes
    </Directory>
</VirtualHost>
```
This will allow the SP to access the dashboard of your AppScale installation. Just make sure to modify the `firewall.conf` file on your AppScale server to restrict outside connections to the dashboard.

**Comment by ldf-** [comment]
Hi @zeroluck.
I don't know if it can help, but I had to build an Authentication module for a GAE/AppScale that talked with multiple backends (including LDAP) and I decided to use [CAS](https://www.apereo.org/projects/cas).

The main reasons were:
- the multi-backend support CAS provides
- you can not (freely open sockets)[https://cloud.google.com/appengine/docs/python/sockets/] to connect to a LDAP server on GAE (http(s) connections are allowed)
