### ISSUE TITLE
Cron URLs Need to Be Encapsulated with Quotes

### ISSUE THREAD

**Issue by caseyoneill** [AppScale/appscale#1873]
When entering jobs into the system crontab, URLs in the curl command need to be encapsulated with quotes. If a url contains multiple parameters and a "&" character, the system shell will interpret anything after the "&" and remove it from the curl command. 

Example cron.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<cronentries>
  <cron>
    <url>clean_data.jsp?param1=valueA&param2=valueB</url>
    <schedule>every hour</schedule>
  </cron>
```

Currently this is entered into the system crontab as:
```
curl -v -H X-Appengine-Cron:true -H X-AppEngine-Fake-Is-Admin:7e564066ae71rtdc177c033dce89e2ff3dbe1cb7 -k -L http://127.0.0.1/clean_data.jsp?param1=valueA&param2=valueB
```

However that will only be sent to the server as: http://127.0.0.1/clean_data.jsp?param1=valueA. Instead the crontab needs to look like the following entry with double quotes surrounding the URL.
```
curl -v -H X-Appengine-Cron:true -H X-AppEngine-Fake-Is-Admin:7e564066ae71rtdc177c033dce89e2ff3dbe1cb7 -k -L "http://127.0.0.1/clean_data.jsp?param1=valueA&param2=valueB"
```

**Comment by cdonati** [comment]
Great catch. I opened a pull request [here](https://github.com/AppScale/appscale/pull/1874) that should be merged shortly.
