### ISSUE TITLE
Image API not working 

### ISSUE THREAD

**Issue by cmmadnat** [AppScale/appscale#1921]
I use Image api to create serving URL from blobkey (java)
`ServingUrlOptions option = ServingUrlOptions.Builder.withBlobKey(blobKey);
            final String servingUrl = imagesService.getServingUrl(option);`
and the serving Url I've got from this function is in local ip like

> http://10.240.0.2:20000/_ah/img/C--I1_h_34B30lGEfHNGLQ==

and the image is unable to be served by the appscale server.

Is there any example on how to use image api or create serving url on appscale? This function works perfectly on appengine.

Thank you

**Comment by menivaitsi** [comment]
It looks like there's a bug in getServingUrl() while picking the correct IP and port for the serving URL.
You can work around this by using [Blobstore serve() call](https://cloud.google.com/appengine/docs/java/blobstore/#Java_Serving_a_blob) for now.

Thank you for reporting the issue.
