### ISSUE TITLE
os.environ['REMOTE_ADDR']  return local server IP

### ISSUE THREAD

**Issue by mikewen** [AppScale/appscale#1969]
I understand Appscale use nginx, so the os.environ['REMOTE_ADDR']  is set to local IP.

Is it a way to get remote IP address inside App engine ?

**Comment by menivaitsi** [comment]
Could you provide more information on what you are trying to achieve?
'NGINX_HOST' is an environ alternative that you can look at for the public IP.

**Comment by mikewen** [comment]
public IP is no good, I am trying to get the remote IP from the user.

I am trying to log the remote IP address of the user when something goes wrong. Also remote IP address of the user provide useful information like location. 
In fact, Google App Engine run-time include location data in request.headers: X-AppEngine-Country , X-AppEngine-Region, X-AppEngine-City, X-AppEngine-CityLatLong 

By the way, self.request.remote_addr also return local IP.

**Comment by menivaitsi** [comment]
Thanks for clarifying. 
The remote IP is forwarded in the X-Real-IP header. You can look for os.environ["HTTP_X_REAL_IP"].
As for the geolocation related headers, those are currently not supported.

If you'd like to play with that you can use the Nginx GeoIP Module and modify the Nginx config for your app to carry those headers along to the application servers.

Let me know if you need help doing that. :)

**Comment by mikewen** [comment]
Thanks a lot! My problem solved!  Have a great weekends!

**Comment by menivaitsi** [comment]
Good to hear. Thanks for using AppScale! :)
