### ISSUE TITLE
Waiting for port 17443 ...

### ISSUE THREAD

**Issue by optimizedsms** [AppScale/appscale#1970]
"When running AppScale on VirtualBox, we've seen problems when VirtualBox 4.1.X is used. Specifically, the AppScale Tools will start up the AppController on port 17443 and then hang at "Please wait for AppScale to start your machines." In this case, the AppScale Tools are waiting for port 17443 to open on the VM, but can't actually reach the VM, which has that port open. Upgrade to VirtualBox 4.2 or newer and that should fix the problem."

"connection refused" for the connect to port 17443. 

I do have a new version of virtualbox...but I still see this.

Any suggestions?

Firewall is down.

**Comment by menivaitsi** [comment]
Are you using the latest AppScale box (2.7.1)?
Can you provide the version of Vagrant you have installed and the host OS?

**Comment by optimizedsms** [comment]
I did didn't use vagrant, I just used the install instructions for the cluster.
So I imagine it is the latest code, the script did a lot checking out!
Don't really want to use vagrant as this will ultimately be a physical, standalone server not a virtualbox when I get the procedure down.

**Comment by menivaitsi** [comment]
OK, that shouldn't be a problem.

Can you provide the steps you're following (setting root password, running bootstrap, etc.)?

**Comment by optimizedsms** [comment]
Actually I seem to have figured it out. 
I reinstalled a 'server' version of ubuntu with absolutely nothing on it. 
Then added sshd, then appscale.
Problem solvled.

**Comment by obino** [comment]
Great. What version of Ubuntu were you using before?

**Comment by optimizedsms** [comment]
First ubuntu desktop, then ubuntu server with LAMP installed.

**Comment by obino** [comment]
Hmm ... I suspect that ubuntu desktop may have a default firewall
configuration that prevented the port from been visible. Thanks for the
information.

On Mon, Mar 07, 2016 at 09:50:52AM -0800, optimizedsms wrote:
> First ubuntu desktop, then ubuntu server with LAMP installed. 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/AppScale/appscale/issues/1970#issuecomment-193367885

-- 
Graziano Obertelli
AppScale Systems, Inc.
