### ISSUE TITLE
create a new user but the dashboard not support upload app?

### ISSUE THREAD

**Issue by fanux** [AppScale/appscale#1996]
Only admin user can upload app?

**Comment by cdonati** [comment]
Hi @fanux. Cloud admin user can grant normal users 'Upload / Remove App' permissions from the dashboard. See the 'Manage Users' link on the left when you are logged in as an admin.

**Comment by fanux** [comment]
Hi @cdonati. I open the permissions for a new user, but still cant upload app.

**Comment by cdonati** [comment]
After sliding the button to 'on' for the user and clicking 'Update Permissions', it may take a minute or so for the change to take effect. Is the 'Upload App' button absent from the left nav for the user, or are you having an issue actually uploading the application?

**Comment by fanux** [comment]
the 'Upload App' button absent from the left nav.

**Comment by cdonati** [comment]
Okay. That's unusual. Do you have ssh access to the deployment? Could you run `python /root/appscale/scripts/describe_user.py "your@user.com"`?

**Comment by fanux** [comment]
python appscale/scripts/describe_user.py "fhtjob@hotmail.com"
user_email:fhtjob@hotmail.com
password:f25881067f698dd5c3ac13d6bcf01180c4dfb51a
num_apps:0
applications:
creation_date:1459316152.0
change_date:1459316225.0
login_date:1459316152.0
visit_cnt:0
appdrop_rem_token:fhtjob@hotmail.com
session_cookie:notSet
cookie_exp:0
cookie_ip:0.0.0.0
ck_sum:0
enabled:true
type:xmpp_user
is_cloud_admin:false
capabilities::upload_app

root@79bf674d2743:~#

**Comment by fanux** [comment]
I hava an other problem, I already upload a app, but the dashboard not show it in app console and delete app view

**Comment by cdonati** [comment]
Okay, my guess is that your dashboard's cron jobs aren't running. Every minute, cron calls the dashboard's `/status/refresh` handler to update the cache. Could you try accessing that handler directly and then seeing if the button shows up?

**Comment by fanux** [comment]
you are right, buttons appear!  How can I run cron jobs? And what reason lead to cron job are't running?

**Comment by cdonati** [comment]
What environment are you running AppScale on? The only time I haven't seen cron running is when running it in a docker container. Even in that case, the fast-start script should start cron for you. If you didn't use the fast-start script and you are running in docker, you can start cron by hand with `/usr/sbin/cron` as root.

If you are running in a typical vm, you can check the status of the cron service with `service cron status` and start it if necessary: `service cron start`.

If cron was already running, I would check the contents of `/etc/cron.d/` to make sure there is an `appscale-appscaledashboard` file in there.

**Comment by fanux** [comment]
yes, I run appscale in docker container.  I start appscale by "fast-start.sh --no-demo-app"

**Comment by cdonati** [comment]
@fanux It turns out there hasn't been a release since that line was added to the fast-start script. For now, you can just start it manually with `/usr/sbin/cron`.

**Comment by menivaitsi** [comment]
This will be the default behavior in the next AppScale version. Closing.
