### ISSUE TITLE
How to build a develop environment in docker container?

### ISSUE THREAD

**Issue by fanux** [AppScale/appscale#1999]
I fork the source code, and clone it to /root derictory, instead the raw appscale derictory, but when I run the fast_start script, it come out an error:
The machine at 192.168.0.2 does not have AppScale 2.7.1 installed. Please login to that machine and ensure that AppScale 2.7.1 is installed on it.
How can I build a develop environment in a correct way?

**Comment by fanux** [comment]
Is there any way to uninstall appscale?

**Comment by menivaitsi** [comment]
@fanux you can follow the getting started guides (www.appscale.com/get-started/) for Docker or building AppScale from source.

I don't think there's currently an easy way to uninstall AppScale since it's conceptually a VM that you can throw away at any time.
