### ISSUE TITLE
How to build a develop environment?

### ISSUE THREAD

**Issue by fanux** [AppScale/appscale#2002]
I install appscale from source code, I fork the project and add some code in it, but I don't know how to run   my new project. If I want to test my features, I need reinstall appscale? Or just edit appscale in /root/appscale directory?

**Comment by menivaitsi** [comment]
@fanux:
There's a few options. You can directly edit the code in /root/appscale or you can copy your code in the AppScale virtual machine before starting AppScale.

If your changes require a build, you'll want to run the [build script](https://github.com/AppScale/appscale/blob/master/debian/appscale_build.sh).

If not, then all you have to do is restart AppScale with appscale down; appscale up.
If you want to be more efficient you can only restart the service that you're editing (e.g. AppManager).
