### ISSUE TITLE
Ask: can appscale run on ArchLinux?

### ISSUE THREAD

**Issue by kokizzu** [AppScale/appscale#2021]
can AppScale run on ArchLinux or archlinux-like (manjaro, etc)
different from debian/ubuntu that use `apt`, archlinux use `pacman`

**Comment by obino** [comment]
Hello Kiswono,

most likely yes, it should be able to run there: you will have to setup
the proper dependencies though. Look into /root/appscale/debian in the
scripts we use: during build you will see errors coming from there, and
you will have to look at them one by one.

Let us know if you have specific questions: we would love to have a
port onto ArchLinux or archlinux-like distro.
