### ISSUE TITLE
Replace Cassandra with Walrus on Redis?

### ISSUE THREAD

**Issue by borg286** [AppScale/appscale#2038]
Walrus is a python library that converts almost all datastore operations with redis calls. Redis can be clustered (index scaling story isn't the greatest). But it seems much more effecient than cassandra. Is cassandra the big memory consummer of AppScale?
I realize that this is only python, but it could serve as a guide for extending to the other app engine languages.
https://github.com/coleifer/walrus

**Comment by cdonati** [comment]
AppScale's datastore server is service (written in Python) that runs as a separate process, so the language of the App Engine app does not matter for the database interface.

It is true that Cassandra tends to have a pretty high memory overhead for applications that have a small amount of data. However, given that Redis is an in-memory database, memory will become an even bigger issue for it than Cassandra once you reach a certain data size.

While I believe that Cassandra is a better _general_ fit for implementing the Cloud Datastore API, I have no doubt that Redis could be a better fit for certain applications. If you are interested in writing an interface for it, I would take a look at https://github.com/AppScale/appscale/blob/master/AppDB/cassandra_env/cassandra_interface.py.

**Comment by borg286** [comment]
There are replacements for Redis that aren't bound by memory. LedisDB,
Ardb, and SSDB come to mind. They can have just as low memory footprint as
you like which holds hot rows. These alternatives get nearly as high QPS,
but still higher that Cassandra on the same number of cores.
