### ISSUE TITLE
I have an error：appscale-upload-app: not found when trying to upload app

### ISSUE THREAD

**Issue by xiaodongmx** [AppScale/appscale#2167]
I upload this error appears when the APP in the appscale dashboard, I have permission to upload APP and delete the App. But I still have this error.
![530 bbk7q l9ng lhi3](https://cloud.githubusercontent.com/assets/22147260/18432873/1dd2e7a0-7917-11e6-85ff-832f9c4eb960.png)

**Comment by cdonati** [comment]
This was fixed recently with https://github.com/AppScale/appscale/pull/2159, which will be included in the next release. If you'd like to fix this particular issue on your current deployment before the next release, you can apply [this commit](https://github.com/AppScale/appscale/pull/2159/commits/cb9dd29966cea02704a1b27c138f736072b1e137) and restart your AppController.
