### ISSUE TITLE
Error when upgrading appscale

### ISSUE THREAD

**Issue by RaiaN** [AppScale/appscale#2240]
Hello.
I am trying to upgrade appscale using the following steps:
1) docker pull appscale:dev
2) docker run -it appscale:dev
3) cd /root/appscale
4) git pull origin master
5) cd debian
6) ./appscale_build.sh
7) cd /root
8) appscale up gives me 
Saw Exception while setting AC parameters: <Fault env:Server: wrong number of arguments (4 for 3): failed to serialize detail object: Cannot map SOAP::Mapping::SOAPException to SOAP/OM.>
AppController at 172.17.0.3 crashed for reasons unknown.

Controller log error:
DjinnServer: OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=unknown state
	/usr/lib/ruby/1.9.1/openssl/ssl-internal.rb:172:in `accept'

Is that possible current github version is broken?

**Comment by menivaitsi** [comment]
If you want to manually upgrade the deployment you need to also pull the latest AppScale Tools repo (steps 3-6 in /root/appscale-tools).

Let us know if that worked.

**Comment by RaiaN** [comment]
Yeah, forgot about it. Thank you!
