### ISSUE TITLE
Define user and ssh port into AppScalefile

### ISSUE THREAD

**Issue by khaledkbadr** [AppScale/appscale#2278]
Hello,
I'm trying to configure my app deployment and by using 
```
# The deployment strategy (roles -> machines) that should be used in this
# AppScale deployment.
# The following is a sample layout for running everything on one machine:
ips_layout :
  master : ip_address
  appengine : ip_address
  database : ip_address
  zookeeper : ip_address
```
It seems that it tries to ssh to the `root@ip_address` and at **port** 22.
My server has port forwarding, and another user than root. Is there anyway to configure the AppScalefile to enable ssh-ing to for example `user@ip_address` at port `9787`

**Comment by obino** [comment]
Hello Khaled,

it is something what we have been looking at, but not at this time. If
you can make the ssh to root works when you are on the machine itself,
then you should be able to start AppScale from the node itself.

What service/infrastructure are you using? Can you send us example on
how AppScale should be reachable (I'm interested in the network part of
course)?

cheers
graziano

**Comment by khaledkbadr** [comment]
Hello Graziano,
I use OpenvCloud infrastructure. It has something called [CloudSpaces](https://gig.gitbooks.io/ovcdoc_public/content/CloudBrokerPortal/CloudSpaces/CloudSpaces.html) which you can create multiple VMs in. I need to `ssh` to each to VM via different port than `22` cause it uses port forwarding to expose ports.

Basically I need to specify port other than 22 to ssh. And I can't find any place in `AppScalefile` configuration to do so. I need to do something like `ssh root@ip_address -p 2200`

**Comment by obino** [comment]
Hello Khaled,

if I may suggest a way forward here, would be to create an ip alias
with the proper public IP, then start the deployment directly onto the
machine. You will then have access to the ports directly.

For example, let's say that 1.2.3.4 is the public IP of your
environment, and that 3.4.5.6 is the private ip. You could do something
like (assuming eth0 is your interface):

  ip addr add 1.2.3.4/32 dev eth0

or

  ifconfig eth0:1 1.2.3.4 up

in case you want to use ifconfig. Check that you publilc ip is
reachable from within your machine

  ssh 1.2.3.4

or

  ping 1.2.3.4

Now you can configure AppScale with an AppScalefile similar to this:

---
ips_layout :
  master : 3.4.5.6 
  appengine : 3.4.5.6
  database : 3.4.5.6
  zookeeper : 3.4.5.6
login: 1.2.3.4

verbose : true
test : true


you should then be able to do appscale up. Perhaps not exactly what
asked for, but I think it may be the quickest way without modifying
AppScale for it.

cheers
graziano
