### ISSUE TITLE
Bootstrap script installs in HOME while code expects code in /root

### ISSUE THREAD

**Issue by khaledkbadr** [AppScale/appscale#2308]
Hey,
I think the [bootstrap](https://raw.githubusercontent.com/AppScale/appscale/master/bootstrap.sh) is designed for docker. The installation is cloning and creating required files at `HOME` location, while code required to start appscale expects files/dirs to be located in `/root`.
Which can be efficient in docker since `HOME` is `/root` but doesn't work on normal machines.

**Comment by cdonati** [comment]
Unfortunately, AppScale still expects to be installed by the root user, which typically has its `HOME` directory as `/root`.

**Comment by khaledkbadr** [comment]
I see, but when I use `sudo -s` to get root user `HOME` still refers to user home. I understand it would be different if I used `sudo -i`. But I think it would be better if it warned me or stopped the installation if `HOME` was not `/root`. What do you think?

**Comment by cdonati** [comment]
Yes, I think that's a good idea until we are more flexible.
