### ISSUE TITLE
os.getuid() returns random uid

### ISSUE THREAD

**Issue by khaledkbadr** [AppScale/appscale#2338]
Hello,
In part of our application we use `expanduser` but the below errors happens where we use it. I investigated running the system's `uids` and that number is not found. Does `appscale` stub or modify `os.getuid()` in any way?
```
  File "/usr/lib/python2.7/posixpath.py", line 269, in expanduser
    userhome = pwd.getpwuid(os.getuid()).pw_dir
KeyError: 'getpwuid(): uid not found: 4294967295'
```

**Comment by cdonati** [comment]
In the sandbox, `getuid` always returns -1. It looks like there's some kind of overflow where `getpwuid` interprets -1 as `2**32 - 1`.

If you want to change it, [here](https://github.com/AppScale/appscale/blob/master/AppServer/google/appengine/tools/devappserver2/python/sandbox.py#L671) is where the override happens.

**Comment by khaledkbadr** [comment]
@cdonati Thanks for the reply
