### ISSUE TITLE
Which logs to look upon when appscale fast-start failed due to "Port 10.23.44.149:17443 did not open in time. Aborting..."

### ISSUE THREAD

**Issue by xuwenbin** [AppScale/appscale#2394]
After installing appscale, tried to start the service with " bash appscale/scripts/fast-start.sh --no-demo-app ".

However, after several minutes, appscale start failed due to Port 10.23.44.149:17443 did not open in time. Aborting...

Opened the log file indicated by the output instruction on screen, couldn't find further clue on how to troubleshoot / investigate the problem.

**Note: The ufw status is inactive in my Ubuntu box.**

Appendix : Entire log content is as follow:

-----------------------------------------------------------------------------------------------------------------

stacktrace : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/scripts/appscale.py", line 43, in main
    appscale.up()
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/appscale.py", line 312, in up
    AppScaleTools.run_instances(run_instances_opts)
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/appscale_tools.py", line 708, in run_instances
    RemoteHelper.start_head_node(options, my_id, node_layout)
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/remote_helper.py", line 264, in start_head_node
    cls.start_remote_appcontroller(head_node, options.keyname, options.verbose)
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/remote_helper.py", line 768, in start_remote_appcontroller
    cls.sleep_until_port_is_open(host, AppControllerClient.PORT, is_verbose)
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/remote_helper.py", line 359, in sleep_until_port_is_open
    "Aborting...".format(host, port))
TimeoutException: Port 10.23.44.149:17443 did not open in time. Aborting...

exception : TimeoutException

tools_version : 3.1.0

platform : Linux-3.13.0-100-generic-x86_64-with-Ubuntu-14.04-trusty

message : Port 10.23.44.149:17443 did not open in time. Aborting...

runtime : CPython

**Comment by cdonati** [comment]
I would recommend taking a look at /var/log/appscale/controller-17443.log (or could be /var/log/appscale/controller.log if you've built from the latest master). That is the log for the process that appscale-tools starts.

**Comment by xuwenbin** [comment]
/var/log/appscale/controller.log says "/bin/bash: /root/appscale/AppController/djinnServer.rb: Permission denied". What does that mean? Any further places I should look up?

BTW, I logged in as root (sudo su), and set HOME to /root.

-wenbin

**Comment by cdonati** [comment]
That error surprises me. It usually indicates that the user trying to run the script does not have permission to execute it, but the script should be executable by default and the user running it should be root.

Is there anything unusual about the environment you are running AppScale on? For example, are you using a non-standard filesystem or running in a docker container? Could you share the output of `ls -l /root/appscale/AppController/djinnServer.rb`?

**Comment by xuwenbin** [comment]
root@10-23-44-149:~# ls -l /root/appscale/AppController/djinnServer.rb
-rw-rw-r-- 1 root root 5794 Mar 26 16:51 /root/appscale/AppController/djinnServer.rb

**Comment by xuwenbin** [comment]
[Update]

After I chmod 777 /root/appscale/AppController/djinnServer.rb, the AppController does start up; nevertheless, fast-start failed at subsequent step - Waiting for head node to initialize...;

I suspect there're other files that require 777 permission. Later on, I'll try to grant 777 to all files under appscale folder, and fast-start it again. Any new findings, will keep this thread posted.

**Comment by cdonati** [comment]
It looks like the djinnServer is missing execute permissions (should be -rwxr-xr-x). I wonder if something went wrong during the git clone process, since the file has execute permissions in the repo.

Did you do a git clone of the repo directly on that machine, or did you transfer the repo from another location using a different method?

**Comment by xuwenbin** [comment]
Indeed, I couldn't manage to clone appscale directly in the VM box from my VPS. So, I ended up with pulling appscale to my local machine (Windows 10) and then uploaded to my VM box through FTP. The execution flag must be lost during that process.

After I granted all files with execution permission in appscale folder in my VM box, appscale service started working.

root@appscale-image0:~# appscale status
----------------------------------------------------------------------------

AppScale is up. All 0 nodes are loaded

APP NAME    HTTP/HTTPS    APPSERVERS/PENDING    REQS. ENQUEUED/TOTAL    STATE

As soon as AppScale Dashboard is started you can visit it at http://10.23.44.149:1080/status and see more about your deployment

[Next steps] I'll try to deploy AppInventor server code to AppScale. My team plans to set up an AppInventor server in China for the original MIT server is based on GAE which is completely banded in China.

**Comment by obino** [comment]
@xuwenbin keep us posted on the progress. For now we are closing this ticket.
