### ISSUE TITLE
Does AppScale support to dump the raw data?

### ISSUE THREAD

**Issue by terry2012** [AppScale/appscale#2504]
One issue of GAE is that it is not easy dump the entire DB raw data. I am wondering whether there is an easy way in AppScale to dump the raw DB data? Thanks.

**Comment by cdonati** [comment]
You have a few options for backing up data in AppScale. Here is a page that describes some of them: https://github.com/AppScale/appscale/wiki/Migration-into-AppScale,-Backup-&-Recovery

If you need something faster and you don't care as much about portability, you can also take Cassandra snapshots using the `appscale-cassandra-backup` script. If you go this route, make sure to either use the same ZooKeeper cluster when restoring or to take a ZooKeeper backup to store along with the Cassandra dump. Using a new ZooKeeper cluster will reset the transaction ID counter for each project ID.

**Comment by scragraham** [comment]
Resolving this ticket, please feel free to re-open the ticket if you have any more questions.
