### ISSUE TITLE
GAE version on BlobInfoFactory

### ISSUE THREAD

**Issue by sammartens1234** [AppScale/appscale#2508]
Hi,

I tried out to deploy my GAE java application on appscale. I changed my maven dependencies of all my GAE components from 1.9.53 to 1.8.4 and compiled it using maven. Next created a tarball.

When uploading the application my Spring configuration does not get loaded:
I have the following spring dependency injection:
<bean id="blobInfoFactory" class="com.google.appengine.api.blobstore.BlobInfoFactory">
	<constructor-arg name="datastoreService" ref="datastoreService" index="0"/>
 </bean>
The error I get is the following:

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'blobInfoFactory' defined in ServletContext resource [/WEB-INF/rest-servlet.xml]: 
Unsatisfied dependency expressed through constructor argument with index 0 of type [com.google.appengine.api.datastore.DatastoreService]: 

Could this be due to the version of the GAE?

Kind regards,

Sam

**Comment by cdonati** [comment]
Hi Sam. I don't have any experience with Spring, and I haven't seen that particular issue before.

Are you creating a tarball from the war directory? Do you have an example application that I can reproduce the issue with? Also, is your app written for the App Engine standard environment or does it run in the flexible environment?

**Comment by sammartens1234** [comment]
I got it to work: i had both versions 1.8.4 and 1.9.53 libraries in my tar

**Comment by scragraham** [comment]
This issue looks to be resolved. Closing.
