### ISSUE TITLE
Cannot configure send mail

### ISSUE THREAD

**Issue by sammartens1234** [AppScale/appscale#2539]
Hi,

I am trying to setup the email. I already did the following: I added a .smtprc file to the /root folder and configured my gmail. 
Next I did a chmod 600 of this file
Next I changed the DEBUG value of the sendmail script to N

I than tried to send an email via msmtp with the command:

echo "Hi, I am there" | msmtp sammartens@gmail,com

This worked fine. I receive the mail and I see the log statement in .smtp.log (which I configured as log file in the .msmtprc config)

But when I try to send an email from within my code, I get "Could not connect to SMTP host: locahost, port: 25". I do not think the sendmail script is called.

**Comment by scragraham** [comment]
Hi @sammartens1234,

Are you still experiencing an issue with this? 

From the error it looks like msmtp is trying to send mail to the server: localhost on port 25. You need to configure msmtp to connect to a valid SMTP server (via the host directive) that will send the email for you.

http://msmtp.sourceforge.net/doc/msmtp.html#General-commands

Thanks,
Steven

**Comment by obino** [comment]
Closing this now: please re-open with more information if needed.
