### ISSUE TITLE
appscale up failed 

### ISSUE THREAD

**Issue by pbymw8iwm** [AppScale/appscale#2540]
root@ubuntu:~/.appscale# appscale up
The AppScalefile is changing, the layout you are using will be invalid soon. Please see our website for more details.
Executing ssh-copy-id for host: 192.168.1.140
root@192.168.1.140's password: 
Generated a new SSH key for this deployment at /root/.appscale/appscale3fb05bc8f17c47668994551e318de327
Starting AppScale 3.3
The AppScalefile is changing, the layout you are using will be invalid soon. Please see our website for more details.
The machine at 192.168.1.140 does not have AppScale installed.

A log with more information is available at
/root/.appscale/log-c4490bcd-43cc-4671-897b-c0fa668f3e4a.
root@ubuntu:~/.appscale# ll
total 28
drwxr-xr-x  2 root root 4096 Aug 30 03:01 ./
drwx--x--x 12 root root 4096 Aug 30 03:00 ../
-rw-------  1 root root 1675 Aug 30 02:58 appscale3fb05bc8f17c47668994551e318de327
-rw-------  1 root root 1675 Aug 30 02:58 appscale3fb05bc8f17c47668994551e318de327.key
-rw-------  1 root root  393 Aug 30 02:58 appscale3fb05bc8f17c47668994551e318de327.pub
-rw-r--r--  1 root root 3207 Aug 30 02:57 AppScalefile
-rw-r--r--  1 root root  939 Aug 30 03:01 log-c4490bcd-43cc-4671-897b-c0fa668f3e4a
root@ubuntu:~/.appscale# cat log-c4490bcd-43cc-4671-897b-c0fa668f3e4a 
stacktrace : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/scripts/appscale.py", line 44, in main
    appscale.up()
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/appscale.py", line 319, in up
    AppScaleTools.run_instances(run_instances_opts)
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/appscale_tools.py", line 713, in run_instances
    head_node.public_ip, options.keyname, options.verbose)
  File "/usr/local/lib/python2.7/dist-packages/appscale/tools/remote_helper.py", line 561, in ensure_machine_is_compatible
    "AppScale installed.".format(host))
AppScaleException: The machine at 192.168.1.140 does not have AppScale installed.

exception : AppScaleException

tools_version : 3.3.1

platform : Linux-4.4.0-31-generic-x86_64-with-Ubuntu-14.04-trusty

message : The machine at 192.168.1.140 does not have AppScale installed.

runtime : CPython

so anyone know what's wrong  when I install appscale by source code.
Thanks !

**Comment by obino** [comment]
Hello,

the error you received indicates that the instances at 192.168.1.140 is
not an appscale image (that is appscale was not installed there). Can
you tell us a bit more how you are trying to start appscale and what is
the machine at 192.168.1.140?

cheers
graziano

-----Original Message-----

**Comment by pbymw8iwm** [comment]
thanks for you reply,I build appscale by these step:
1. there is no error when I build appscale, and I'm sure I build appscale at 192.168.1.140.
the teminal has refresh the build infomation about appscale, so I just only provide this successful appscale-tools msg:

Successfully built appscale-tools
Installing collected packages: oauth2client
  Found existing installation: oauth2client 4.1.2
    Uninstalling oauth2client-4.1.2:
      Successfully uninstalled oauth2client-4.1.2
Successfully installed oauth2client-4.0.0
AppScale tools installation completed successfully!

2. when build succeed, I cd /root(or cd ~) and execute command "appscale init cluster",the current directory (/root)  will create a new directory names ".appscale", and then I edit AppScalefile, the part of the contents show below：
root@ubuntu:~# cat AppScalefile 
---
# The deployment strategy (roles -> machines) that should be used in this
# AppScale deployment.
# The following is a sample layout for running everything on one machine:
ips_layout :
  master : 192.168.1.140
  appengine : 192.168.1.140
  database : 192.168.1.140
  zookeeper : 192.168.1.140
3. copy AppScalefile to .appscale and cd .appscale,
last I run appscale up and the error occurred
4. I have a question that why I execute command "appscale init cluster" at /root, edit  Appscalefile and then execute command "appscale up",the terminal echo message below :

root@ubuntu:~# appscale up
while parsing a block mapping
  in "<string>", line 5, column 1:
    ips_layout :
    ^
expected <block end>, but found '<block mapping start>'
  in "<string>", line 40, column 2:
     verbose : True
     ^

A log with more information is available at
/root/.appscale/log-c3a73a5e-e11f-4db4-a22f-541a948a4e87.

**Comment by pbymw8iwm** [comment]
I build appscle at China,I think maybe there are some packages download failed when network is weak and the script will skip them, I will try more times  in sure  all the packages needed download successfully.

Regards
Gao

**Comment by scragraham** [comment]
Resolving this issue, it sounds like it was a network issue. If you have more problems feel free to open up another issue. 

Thanks,
Steven
