### ISSUE TITLE
Add information about supported Go version and supported Go GAE SDK to FAQ

### ISSUE THREAD

**Issue by lennrt** [AppScale/appscale#2734]
I noticed that under the FAQ section titled ["What version of the GAE API do you support?"](https://github.com/AppScale/appscale/wiki/FAQs#what-version-of-the-gae-api-do-you-support) there is no information about which version of the Go GAE SDK is supported by AppScale. Based on information in the `RELEASE` document (https://github.com/AppScale/appscale/blob/master/RELEASE#L947) it appears that AppScale supports version 1.5.0 of the Go GAE SDK. However, this information is from 2011. Is this still the latest version that is supported?

Additionally, the FAQ section titled ["What languages do you support?"](https://github.com/AppScale/appscale/wiki/FAQs#what-languages-do-you-support) makes no mention of the supported version of the Go language. Based on the `RELEASE` it looks like this is Go version 1.6 (https://github.com/AppScale/appscale/blob/master/RELEASE#L168). 

Are these values correct? If so, I will add a section to the FAQ about this. I just want to be sure that this information is correct prior to doing so.

**Comment by cdonati** [comment]
Good point. I just updated the FAQ. To answer your question, our Go runtime environment is based on the 1.9.48 SDK which supports Go 1.6.
