### ISSUE TITLE
channel API not working

### ISSUE THREAD

**Issue by josephcarington** [AppScale/appscale#2789]
Environment: clean xenial machine; appscale installed per instructions with boostrap.sh; environment is functioning as expected

Issue: using the channel API sample from http://github.com/AppScale/sample-apps results in this error anytime the **channel.create_channel** method is called:

**SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)**

Will AppScale continue to support the Channel API, or are there plans to deprecate and retire it, as Google has done?  And, if so, will there be something to replace it?

**Comment by cdonati** [comment]
It looks like it's currently working on Trusty, but it's broken on Xenial. We need to add automated tests for that API.

It should work again on Xenial after applying #2791 and #2792.

We don't plan on deprecating the Channel API. The dependencies and functionality are very similar to the XMPP API, so we wouldn't gain much (in terms of reduced complexity) by removing it.
