### ISSUE TITLE
persistent sessions do not work as expected

### ISSUE THREAD

**Issue by pphegde** [AppScale/appscale#3014]
Appscale 3.6, App is in Java.
When we have 2 instances for the appserver, we are observing that our application users are getting logged out  - i.e session is invalidated. We think that this happens when the requests are served by the instance which is not the same as the one which was used to login. 

Including @cdonati's assessment:

I don't think we have any automated tests for the Java runtime's sessions implementation. My guess is that the SDK is storing session data in memory rather than using memcache and the datastore.

**Comment by cdonati** [comment]
@pphegde I can confirm this is an issue, and we now have an automated test for it. I'll update this thread when we have a fix available.
